---
- name: Check system utilization
  hosts: all
  gather_facts: no
  tasks:
    - name: Check memory usage
      shell: free | grep Mem | awk '{print $3/$2 * 100.0}'
      register: memory_usage

    - name: Debug memory usage
      debug:
        msg: "Memory usage: {{ memory_usage.stdout | round(2) }}%"
    
    - name: Check CPU usage
      shell: mpstat 1 1 | grep "Average" | awk '{print 100 - $12}'
      register: cpu_usage

    - name: Debug CPU usage
      debug:
        msg: "CPU usage: {{ cpu_usage.stdout | round(2) }}%"
    
    - name: Check disk usage
      shell: df -h --total | grep 'total' | awk '{print $5}' | sed 's/%//'
      register: disk_usage

    - name: Debug disk usage
      debug:
        msg: "Disk usage: {{ disk_usage.stdout | int }}%"

    - name: Report high memory usage
      debug:
        msg: "Warning: Memory usage is above 70% (Current: {{ memory_usage.stdout | round(2) }}%)"
      when: memory_usage.stdout | float > 70

    - name: Report high CPU usage
      debug:
        msg: "Warning: CPU usage is above 70% (Current: {{ cpu_usage.stdout | round(2) }}%)"
      when: cpu_usage.stdout | float > 70

    - name: Report high disk usage
      debug:
        msg: "Warning: Disk usage is above 70% (Current: {{ disk_usage.stdout | int }})%"
      when: disk_usage.stdout | int > 70
